### ISSUE TITLE
Support functions/variables outside classes

### ISSUE THREAD

**Issue by senier** [Componolit/capdpa#55]
While not required in Genode, this will be a fundamental show stopper to handle any other code base. Implement support for binding functions and variables at namespace (including the root namespace) level.

**Comment by jklmnn** [comment]
Are there any (non-working) tests for this case? Afaict this should already work since we make no distinction between functions inside and outside classes and everything that doesn't reside in a namespace or class should appear in the project package.
The only problem I can see now is that functions outside of classes are generated falsely to Ada since they're not marked as static yet.

**Comment by senier** [comment]
Functions and variables outside classes got ignored silently during code generation as children got filtered for constants, enums and type definitions in `ir_namespace.py`. Also, `VAR_DECL` was ignored in `__convert_children` in `cxx.py`, so that plain variables would not even show up in the IR. I had to distinguish class members, variables and function arguments to get the mangling right (we wanted to do this anyways). Next step is build some validation tests for that feature in #52.

**Comment by senier** [comment]
Done in 976e319
